discord:
  token: ${DISCORD_TOKEN}
  client_id: ${DISCORD_CLIENT_ID}

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  dbname: ${DB_NAME}
  sslmode: ${DB_SSLMODE} 
